# Generated by Django 4.1.3 on 2022-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TgUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(unique=True, verbose_name="Chat id"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
            ],
        ),
    ]
