name: CI actions
on: [ push ]
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: docker build
        run: docker build -t ${{ secrets.DOCKER_NAME }}/todolist-course-work6:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker hub login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_NAME }} --password-stdin
      - name: docker push
        run: docker push ${{ secrets.DOCKER_NAME }}/todolist-course-work6:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG_MODE: ${{ secrets.DEBUG_MODE }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      VK_OAUTH2_KEY: ${{ secrets.VK_OAUTH2_KEY }}
      VK_OAUTH2_SECRET: ${{ secrets.VK_OAUTH2_SECRET }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: clone code
        uses: actions/checkout@v3

      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
          cat .env_example  | envsubst > deploy/.env

      - name: copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deploy/docker-compose.yaml,deploy/.env_example"
          target: "todolist"
          strip_components: 1

      - name: Clear before Deploy
        if: always()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd todolist
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker system prune -a -f

      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd todolist
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d
